policy_maps:
  qos:
    - name: PM_REPLICATION_LD
      classes:
        - name: CM_REPLICATION_LD
          set:
            dscp: af11
            traffic_class: 2
            drop_precedence: 1
          police:
            rate:
              lower_rate: 10
              rate_unit: kbps
              lower_rate_burst_size: 260
              burst_size_unit: kbytes
              higher_rate: 30
              higher_rate_burst_size: 270
              action: drop-precedence
        - name: CM_REPLICATION_LD_2
          set:
            dscp: af11
            traffic_class: 2
    - name: PM_REPLICATION_LD2
      classes:
        - name: CM_REPLICATION_LD
          set:
            dscp: af11
            cos: 4
          police:
            cir:
              cir_rate: 12
              cir_unit: kbps
              bc: 267
              bc_unit: kbytes
    - name: PM_REPLICATION_LD3
      classes:
        - name: CM_REPLICATION_LD
          set:
            dscp: af11
            cos: 6
          police:
            rate:
              lower_rate: 10
              rate_unit: kbps
              lower_rate_burst_size: 260
              burst_size_unit: kbytes
  pbr:
    - name: PM_PBR_BREAKOUT
      classes:
        - name: CM_PBR_EXCLUDE
        - name: CM_PBR_INCLUDE
          set:
            nexthop:
              ip_address: 192.168.4.2
              recursive: true
