---
### Port-Channel Interfaces ###
# Testing deprecated keys for switchport config in port-channel_interfaces
port_channel_interfaces:
  # Testing deprecated esi and rt variables on port-channel interfaces/subinterfaces
  - name: Port-Channel1
    description: SRV01_bond0
    vlans: 2-3000
    mode: trunk
    esi: 0000:0000:0404:0404:0303
    rt: 04:04:03:03:02:02
    lacp_id: 0303.0202.0101

  - name: Port-Channel2
    mode: access
    vlans: 100

  - name: Port-Channel3
    mode: trunk
    vlans: 110
    native_vlan: 10
    trunk_groups:
      - group1
      - group2

  - name: Port-Channel4
    native_vlan_tag: true
    native_vlan: 20
    mode: trunk phone
    phone:
      vlan: 20
      trunk: tagged

  - name: Port-Channel5
    vlan_translations:
      - from: 23
        to: 50
        direction: in
      - from: 25
        to: 49
        direction: out
      - from: 34
        to: 60
        direction: both
    trunk_private_vlan_secondary: true
    pvlan_mapping: "2,3,4"
