name: "Collection code testing"

"on": pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  # Set -vvv is ACTIONS_STEP_DEBUG is set
  # Apparently it is set in secrets when running with debug
  ANSIBLE_VERBOSITY: ${{ secrets.ACTIONS_STEP_DEBUG && 3 || 0 }}
  AVD_NEVER_RUN_FROM_SOURCE: 1
  PY_COLORS: 1 # allows molecule colors to be passed to GitHub Actions
  ANSIBLE_FORCE_COLOR: 1 # allows ansible colors to be passed to GitHub Actions

jobs:
  file-changes:
    runs-on: ubuntu-latest
    outputs:
      eos_design: ${{ steps.filter.outputs.eos_design }}
      config_gen: ${{ steps.filter.outputs.config_gen }}
      cloudvision: ${{ steps.filter.outputs.cloudvision }}
      dhcp: ${{ steps.filter.outputs.dhcp }}
      plugins: ${{ steps.filter.outputs.plugins }}
      requirements: ${{ steps.filter.outputs.requirements }}
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            eos_design:
              - 'ansible_collections/arista/avd/roles/eos_designs/*'
              - 'ansible_collections/arista/avd/roles/eos_designs/**/*'
              - '.github/workflows/pull-request-management.yml'
              - 'ansible_collections/arista/avd/molecule/*'
              - 'ansible_collections/arista/avd/molecule/**/*'
              - 'python-avd/pyavd/_eos_designs/*'
              - 'python-avd/pyavd/_eos_designs/**/*'
              - '!ansible_collections/arista/avd/roles/eos_config_deploy_cvp/*'
              - '!ansible_collections/arista/avd/roles/eos_config_deploy_cvp/**/*'
              - '!ansible_collections/arista/avd/molecule/cvp_configlet_upload/*'
              - '!ansible_collections/arista/avd/molecule/cvp_configlet_upload/**/*'
            config_gen:
              - 'ansible_collections/arista/avd/roles/eos_cli_config_gen/*'
              - 'ansible_collections/arista/avd/roles/eos_cli_config_gen/**/*'
              - '.github/workflows/pull-request-management.yml'
              - 'ansible_collections/arista/avd/molecule/eos_cli_config_gen*/*'
              - 'ansible_collections/arista/avd/molecule/eos_cli_config_gen*/**/*'
              - 'python-avd/pyavd/_eos_cli_config_gen/*'
              - 'python-avd/pyavd/_eos_cli_config_gen/**/*'
            validate_state:
              - 'ansible_collections/arista/avd/roles/eos_validate_state/*'
              - 'ansible_collections/arista/avd/roles/eos_validate_state/**/*'
            cloudvision:
              - 'ansible_collections/arista/avd/roles/eos_config_deploy_cvp/*'
              - 'ansible_collections/arista/avd/roles/eos_config_deploy_cvp/**/*'
              - 'ansible_collections/arista/avd/molecule/cvp_configlet_upload/*'
              - 'ansible_collections/arista/avd/molecule/cvp_configlet_upload/**/*'
              - '.github/workflows/pull-request-management.yml'
            dhcp:
              - 'ansible_collections/arista/avd/roles/dhcp_provisioner/*'
              - 'ansible_collections/arista/avd/roles/dhcp_provisioner/**/*'
              - '.github/workflows/pull-request-management.yml'
            plugins:
              - 'ansible_collections/arista/avd/plugins/filter/**'
              - 'ansible_collections/arista/avd/plugins/test/**'
            requirements:
              - 'ansible_collections/arista/avd/requirements.txt'
              - 'ansible_collections/arista/avd/requirements-dev.txt'
              - 'ansible_collections/arista/avd/meta/runtime.yml'
              - '.github/requirements-ci.txt'
              - '.github/workflows/pull-request-management.yml'
            docs:
              - '.github/workflows/pull-request-management.yml'
              - 'mkdocs.yml'
              - 'ansible_collections/arista/avd/docs/**'
              - 'ansible_collections/arista/avd/roles/**/*.md'
              - 'ansible_collections/arista/avd/**/*.md'
              - 'ansible_collections/arista/avd/README.md'
              - 'ansible_collections/arista/avd/**/*.schema.yml'
            pyavd:
              - 'python_avd/*'
              - 'python_avd/**/*'
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: 
      image: ubuntu:latest
      options: --cpus 1

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.10
            3.11
            3.12
            3.13
      - name: Install dependencies
        run: |
          pip install "ansible-core<2.19.0" -r .github/requirements-ci.txt --upgrade
          
      - name: Get container ID
        id: container-info
        run: echo "::set-output name=id::$(docker ps -aqf 'name=github-actions-job')"

      - name: Commit the container changes to an image
        run: |
          docker commit -m "Added Python and dependencies" -a "GitHub Actions" ${{ steps.container-info.outputs.id }} my-python-app:latest

      - name: Save image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-app-image
          path: ${{ github.workspace }}/.docker/my-python-app:latest.tar

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Build the Docker image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: false
      #     tags: my-python-app:latest
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Commit the container changes to an image
      #   run: |
      #     CONTAINER_ID=$(docker ps -aqf "name=github-actions-job")
      #     docker commit -m "Added Python and dependencies" -a "GitHub Actions" $CONTAINER_ID my-python-app:latest

      # - name: Save image as artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: python-app-image
      #     path: ${{ github.workspace }}/.docker/my-python-app:latest.tar

  # reuse-container-job:
  #   name: reuse first job
  #   runs-on: ubuntu-latest
  #   needs: [ container-job ]
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: project
  #         path: /tmp

  #     - name: Load image
  #       run: docker load --input /tmp/project.tar

  #     - name: Run
  #       uses: addnab/docker-run-action@v3
  #       with:
  #         image: project-image
  #         run: |
  #           pip list
