name: "Collection code testing"

"on": pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  # Set -vvv is ACTIONS_STEP_DEBUG is set
  # Apparently it is set in secrets when running with debug
  ANSIBLE_VERBOSITY: ${{ secrets.ACTIONS_STEP_DEBUG && 3 || 0 }}
  AVD_NEVER_RUN_FROM_SOURCE: 1
  PY_COLORS: 1 # allows molecule colors to be passed to GitHub Actions
  ANSIBLE_FORCE_COLOR: 1 # allows ansible colors to be passed to GitHub Actions

jobs:
  file-changes:
    runs-on: ubuntu-latest
    outputs:
      eos_design: ${{ steps.filter.outputs.eos_design }}
      config_gen: ${{ steps.filter.outputs.config_gen }}
      cloudvision: ${{ steps.filter.outputs.cloudvision }}
      dhcp: ${{ steps.filter.outputs.dhcp }}
      plugins: ${{ steps.filter.outputs.plugins }}
      requirements: ${{ steps.filter.outputs.requirements }}
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            eos_design:
              - 'ansible_collections/arista/avd/roles/eos_designs/*'
              - 'ansible_collections/arista/avd/roles/eos_designs/**/*'
              - '.github/workflows/pull-request-management.yml'
              - 'ansible_collections/arista/avd/molecule/*'
              - 'ansible_collections/arista/avd/molecule/**/*'
              - 'python-avd/pyavd/_eos_designs/*'
              - 'python-avd/pyavd/_eos_designs/**/*'
              - '!ansible_collections/arista/avd/roles/eos_config_deploy_cvp/*'
              - '!ansible_collections/arista/avd/roles/eos_config_deploy_cvp/**/*'
              - '!ansible_collections/arista/avd/molecule/cvp_configlet_upload/*'
              - '!ansible_collections/arista/avd/molecule/cvp_configlet_upload/**/*'
            config_gen:
              - 'ansible_collections/arista/avd/roles/eos_cli_config_gen/*'
              - 'ansible_collections/arista/avd/roles/eos_cli_config_gen/**/*'
              - '.github/workflows/pull-request-management.yml'
              - 'ansible_collections/arista/avd/molecule/eos_cli_config_gen*/*'
              - 'ansible_collections/arista/avd/molecule/eos_cli_config_gen*/**/*'
              - 'python-avd/pyavd/_eos_cli_config_gen/*'
              - 'python-avd/pyavd/_eos_cli_config_gen/**/*'
            validate_state:
              - 'ansible_collections/arista/avd/roles/eos_validate_state/*'
              - 'ansible_collections/arista/avd/roles/eos_validate_state/**/*'
            cloudvision:
              - 'ansible_collections/arista/avd/roles/eos_config_deploy_cvp/*'
              - 'ansible_collections/arista/avd/roles/eos_config_deploy_cvp/**/*'
              - 'ansible_collections/arista/avd/molecule/cvp_configlet_upload/*'
              - 'ansible_collections/arista/avd/molecule/cvp_configlet_upload/**/*'
              - '.github/workflows/pull-request-management.yml'
            dhcp:
              - 'ansible_collections/arista/avd/roles/dhcp_provisioner/*'
              - 'ansible_collections/arista/avd/roles/dhcp_provisioner/**/*'
              - '.github/workflows/pull-request-management.yml'
            plugins:
              - 'ansible_collections/arista/avd/plugins/filter/**'
              - 'ansible_collections/arista/avd/plugins/test/**'
            requirements:
              - 'ansible_collections/arista/avd/requirements.txt'
              - 'ansible_collections/arista/avd/requirements-dev.txt'
              - 'ansible_collections/arista/avd/meta/runtime.yml'
              - '.github/requirements-ci.txt'
              - '.github/workflows/pull-request-management.yml'
            docs:
              - '.github/workflows/pull-request-management.yml'
              - 'mkdocs.yml'
              - 'ansible_collections/arista/avd/docs/**'
              - 'ansible_collections/arista/avd/roles/**/*.md'
              - 'ansible_collections/arista/avd/**/*.md'
              - 'ansible_collections/arista/avd/README.md'
              - 'ansible_collections/arista/avd/**/*.schema.yml'
            pyavd:
              - 'python_avd/*'
              - 'python_avd/**/*'
  container-job-1:
    runs-on: ubuntu-latest
    container: 
      image: ubuntu:latest
      options: --cpus 1

    outputs:
      image_tag: ${{ steps.build-image.outputs.image_tag }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Convert GitHub username to lowercase
        id: lowercase
        run: |
          echo "::set-output name=lowercase::$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ steps.lowercase.outputs.lowercase }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Dockerfile dynamically
        run: |
          echo "Creating Dockerfile..."
          cat <<EOF > Dockerfile
          # Base image
          FROM ghcr.io/shivani-gslab/avd/python:0.0.1
          ENV PIP_CACHE_DIR=/cache
          ARG PYTHON_VERSIONS="3.10 3.11 3.12 3.13"

          RUN mkdir -p /cache
          WORKDIR /avd

          RUN apt-get update && apt-get install -y --no-install-recommends \
              openssh-client git make python3-pip python3-dev docker.io && \
              pip install --cache-dir=$PIP_CACHE_DIR uv --break-system-packages && \
              uv python install 3.10 3.11 3.12 3.13

          RUN if [ -d ".git" ]; then \
            echo "Repository exists, pulling latest changes..."; \
            git pull; \
          else \
            echo "Cloning repository..."; \
            git clone https://github.com/${{ github.repository }}; \
          fi
          WORKDIR /
          RUN for version in 3.10 3.11 3.12 3.13; do \
              echo "Checking if virtual environment for Python \$version exists..." && \
              if [ ! -d "UV\$version" ]; then \
                  echo "Virtual environment for Python \$version does not exist. Creating it..." && \
                  uv venv --python \$version UV\$version && \
                  UV\$version/bin/python -m ensurepip --upgrade && \
                  echo "Virtual environment UV\$version created and pip upgraded."; \
              else \
                  echo "Virtual environment for Python \$version already exists, skipping creation..."; \
              fi && \
              UV\$version/bin/python -m pip install --cache-dir=$PIP_CACHE_DIR \
                  mock pytest pytest-mock pytest-xdist pyyaml "ansible-core<2.19.0" \
                  -r /avd/ansible_collections/arista/avd/requirements-dev.txt --upgrade && \
              echo "Dependencies installed for Python \$version in virtual environment UV\$version."; \
          done

          RUN apt-get clean && \
              rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

          CMD ["python"]
          EOF
          echo "Dockerfile created successfully."

      - name: Build Docker Image
        id: build-image
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-8)
          IMAGE_TAG=ghcr.io/${{ steps.lowercase.outputs.lowercase }}/avd/python:${{ github.run_number }}-$SHORT_SHA
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          echo "::set-output name=image_tag::$IMAGE_TAG"

  container-job-2:
    needs: container-job-1
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.container-job-1.outputs.image_tag }}
      #image: ghcr.io/shivani-gslab/avd/python:497-92985fc8
      options: --cpus 1
      # credentials:
      #   username: shivani-gslab
      #   password: ${{ secrets.github_token }}
    outputs:
      image_tag: ${{ steps.wheel-image-tag.outputs.wheel_image_tag }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Convert GitHub username to lowercase
        id: lowercase
        run: |
          echo "::set-output name=lowercase::$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ steps.lowercase.outputs.lowercase }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Additional Task in Second Container
        id: wheel-image-tag
        run: |
          cd python-avd

          # Build the wheel package
          echo "Building the wheel package..."
          python3 -m pip install --break-system-packages build
          python3 -m build --wheel --outdir /tmp/wheels
          # Install pyavd
          /UV3.10/bin/python -m pip install /tmp/wheels/*.whl
          /UV3.11/bin/python -m pip install /tmp/wheels/*.whl
          /UV3.12/bin/python -m pip install /tmp/wheels/*.whl
          /UV3.13/bin/python -m pip install /tmp/wheels/*.whl
          
          # Generate a unique tag using run number and truncated commit SHA
          WHEEL_IMAGE_TAG=${{ needs.container-job-1.outputs.image_tag }}-2
          # docker build -t $WHEEL_IMAGE_TAG .
          # docker push $WHEEL_IMAGE_TAG
          # Build the updated image from the current container state
          docker commit $(docker ps -q --filter ancestor=${{ needs.container-job-1.outputs.image_tag }}) $WHEEL_IMAGE_TAG

          # Push the updated image to GitHub Container Registry
          docker push $WHEEL_IMAGE_TAG
          echo "::set-output name=wheel_image_tag::$WHEEL_IMAGE_TAG"
          

  reuse-ghcr-image:
    name: reuse first job
    needs: container-job-2
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.container-job-2.outputs.wheel_image_tag }}
      #image: ghcr.io/shivani-gslab/avd/python:525-33cb46b7
      options: --cpus 1
      credentials:
        username: shivani-gslab
        password: ${{ secrets.github_token }}

    strategy:
      matrix:
        task:
          - name: Execute Ansible unit tests 3.12
            command: ". /UV3.12/bin/activate && cd ansible_collections/arista/avd && ansible-test units -vv"
          - name: Execute Ansible integration tests 3.12
            command: ". /UV3.12/bin/activate && cd ansible_collections/arista/avd && ansible-test integration -vv"
          - name: Execute Ansible integration tests 3.13
            command: ". /UV3.13/bin/activate && cd ansible_collections/arista/avd && ansible-test integration -vv"
          - name: Execute Ansible sanity tests 3.13
            command: ". /UV3.13/bin/activate && cd ansible_collections/arista/avd && ansible-test sanity --color yes -v"
          - name: Execute Ansible sanity tests 3.12
            command: ". /UV3.12/bin/activate && cd ansible_collections/arista/avd && ansible-test sanity --color yes -v"
          - name: Execute Ansible lint tests 3.11
            command: ". /UV3.11/bin/activate && ansible-galaxy collection install -r ansible_collections/arista/avd/collections.yml && cd ansible_collections/arista/avd && ansible-lint --force-color --strict -v"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
    
      - name: Run Task - ${{ matrix.task.name }}
        run: |
          git config --global --add safe.directory /__w/avd/avd
          pwd
          ls -l
          cd ..
          ls -l
          cd ..
          ls -l
          cd ..
          ls -l
          cd ..
          pwd
          ls -l
          ${{ matrix.task.command }}
