name: "Collection code testing"

"on": pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  # Set -vvv is ACTIONS_STEP_DEBUG is set
  # Apparently it is set in secrets when running with debug
  ANSIBLE_VERBOSITY: ${{ secrets.ACTIONS_STEP_DEBUG && 3 || 0 }}
  AVD_NEVER_RUN_FROM_SOURCE: 1
  PY_COLORS: 1 # allows molecule colors to be passed to GitHub Actions
  ANSIBLE_FORCE_COLOR: 1 # allows ansible colors to be passed to GitHub Actions

jobs:
  file-changes:
    runs-on: ubuntu-latest
    outputs:
      eos_design: ${{ steps.filter.outputs.eos_design }}
      config_gen: ${{ steps.filter.outputs.config_gen }}
      cloudvision: ${{ steps.filter.outputs.cloudvision }}
      dhcp: ${{ steps.filter.outputs.dhcp }}
      plugins: ${{ steps.filter.outputs.plugins }}
      requirements: ${{ steps.filter.outputs.requirements }}
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            eos_design:
              - 'ansible_collections/arista/avd/roles/eos_designs/*'
              - 'ansible_collections/arista/avd/roles/eos_designs/**/*'
              - '.github/workflows/pull-request-management.yml'
              - 'ansible_collections/arista/avd/molecule/*'
              - 'ansible_collections/arista/avd/molecule/**/*'
              - 'python-avd/pyavd/_eos_designs/*'
              - 'python-avd/pyavd/_eos_designs/**/*'
              - '!ansible_collections/arista/avd/roles/eos_config_deploy_cvp/*'
              - '!ansible_collections/arista/avd/roles/eos_config_deploy_cvp/**/*'
              - '!ansible_collections/arista/avd/molecule/cvp_configlet_upload/*'
              - '!ansible_collections/arista/avd/molecule/cvp_configlet_upload/**/*'
            config_gen:
              - 'ansible_collections/arista/avd/roles/eos_cli_config_gen/*'
              - 'ansible_collections/arista/avd/roles/eos_cli_config_gen/**/*'
              - '.github/workflows/pull-request-management.yml'
              - 'ansible_collections/arista/avd/molecule/eos_cli_config_gen*/*'
              - 'ansible_collections/arista/avd/molecule/eos_cli_config_gen*/**/*'
              - 'python-avd/pyavd/_eos_cli_config_gen/*'
              - 'python-avd/pyavd/_eos_cli_config_gen/**/*'
            validate_state:
              - 'ansible_collections/arista/avd/roles/eos_validate_state/*'
              - 'ansible_collections/arista/avd/roles/eos_validate_state/**/*'
            cloudvision:
              - 'ansible_collections/arista/avd/roles/eos_config_deploy_cvp/*'
              - 'ansible_collections/arista/avd/roles/eos_config_deploy_cvp/**/*'
              - 'ansible_collections/arista/avd/molecule/cvp_configlet_upload/*'
              - 'ansible_collections/arista/avd/molecule/cvp_configlet_upload/**/*'
              - '.github/workflows/pull-request-management.yml'
            dhcp:
              - 'ansible_collections/arista/avd/roles/dhcp_provisioner/*'
              - 'ansible_collections/arista/avd/roles/dhcp_provisioner/**/*'
              - '.github/workflows/pull-request-management.yml'
            plugins:
              - 'ansible_collections/arista/avd/plugins/filter/**'
              - 'ansible_collections/arista/avd/plugins/test/**'
            requirements:
              - 'ansible_collections/arista/avd/requirements.txt'
              - 'ansible_collections/arista/avd/requirements-dev.txt'
              - 'ansible_collections/arista/avd/meta/runtime.yml'
              - '.github/requirements-ci.txt'
              - '.github/workflows/pull-request-management.yml'
            docs:
              - '.github/workflows/pull-request-management.yml'
              - 'mkdocs.yml'
              - 'ansible_collections/arista/avd/docs/**'
              - 'ansible_collections/arista/avd/roles/**/*.md'
              - 'ansible_collections/arista/avd/**/*.md'
              - 'ansible_collections/arista/avd/README.md'
              - 'ansible_collections/arista/avd/**/*.schema.yml'
            pyavd:
              - 'python_avd/*'
              - 'python_avd/**/*'
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: [3.12] # Python versions
    # Docker Hub image that `container-job` executes in
    container: 
      image: ubuntu:latest
      options: --cpus 1

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Docker
        run: |
          apt-get update
          apt-get install -y docker.io
      
      - name: Convert GitHub username to lowercase
        id: lowercase
        run: |
          echo "::set-output name=lowercase::$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ steps.lowercase.outputs.lowercase }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Dynamically create Dockerfile
      - name: Create Dockerfile dynamically
        run: |
          echo "Creating Dockerfile..."
          cat <<EOF > Dockerfile
          FROM ubuntu:latest

          # Install pre-requisites
          RUN apt-get update && apt-get install -y --no-install-recommends openssh-client git make python3-pip && apt-get clean

          # Install UV
          RUN pip install uv --break-system-packages

          # Install python versions
          RUN uv python install 3.10 3.11 3.12 3.13

          # Create a directory to store cached dependencies
          ENV PIP_CACHE_DIR=/cache
          RUN mkdir -p /cache

          # Clone the repository in the Docker image
          RUN git clone https://github.com/${{ github.repository }}

          WORKDIR /avd

          # Build the wheel package
          RUN cd python-avd && \
            python3 -m pip install --break-system-packages build && \
            python3 -m build --wheel --outdir /tmp/wheels
 
          WORKDIR /
          # Create virtual env
          RUN uv venv --python 3.10 UV3.10  && \
              UV3.10/bin/python -m ensurepip --upgrade 
          RUN uv venv --python 3.11 UV3.11 && \
              UV3.11/bin/python -m ensurepip --upgrade 
          RUN uv venv --python 3.12 UV3.12 && \
              UV3.12/bin/python -m ensurepip --upgrade 
          RUN uv venv --python 3.13 UV3.13 && \
              UV3.13/bin/python -m ensurepip --upgrade 

          # # Activate virtual env
          RUN . UV3.12/bin/activate && \
            cd avd/ && \
            ../UV3.10/bin/python -m pip install --cache-dir=$PIP_CACHE_DIR "ansible-core<2.19.0" \
            -r ansible_collections/arista/avd/requirements-dev.txt --upgrade && \
            ../UV3.10/bin/python -m pip install /tmp/wheels/*.whl

          # # Activate virtual env
          RUN . UV3.12/bin/activate && \
            cd avd/ && \
            ../UV3.11/bin/python -m pip install --cache-dir=$PIP_CACHE_DIR "ansible-core<2.19.0" \
            -r ansible_collections/arista/avd/requirements-dev.txt --upgrade && \
            ../UV3.11/bin/python -m pip install /tmp/wheels/*.whl

          # Activate virtual env
          RUN . UV3.12/bin/activate && \
            cd avd/ && \
            ../UV3.12/bin/python -m pip install --cache-dir=$PIP_CACHE_DIR mock pytest pytest-mock pytest-xdist pyyaml "ansible-core<2.19.0" \
            -r ansible_collections/arista/avd/requirements-dev.txt --upgrade && \
            ../UV3.12/bin/python -m pip install /tmp/wheels/*.whl

          # Activate virtual env
          RUN . UV3.13/bin/activate && \
            cd avd/ && \
            ../UV3.13/bin/python -m pip install --cache-dir=$PIP_CACHE_DIR "ansible-core<2.19.0" \
            -r ansible_collections/arista/avd/requirements-dev.txt --upgrade && \
            ../UV3.13/bin/python -m pip install /tmp/wheels/*.whl

          CMD ["python"]
          EOF
          echo "Dockerfile created successfully."

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ steps.lowercase.outputs.lowercase }}/avd/python_avd:0.0.1 .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ steps.lowercase.outputs.lowercase }}/avd/python_avd:0.0.1

  # reuse_container_image:
  #   name: Reuse image with ghcr credentials
  #   runs-on: ubuntu-latest
  #   needs: [container-job]
  #   container:
  #     image: ghcr.io/shivani-gslab/avd/python_avd:0.0.1
  #     credentials:
  #       username: ${{ github.repository_owner }}
  #       password: ${{ secrets.GITHUB_TOKEN }}  
  #   steps:
  #     - name: Check for dockerenv file
  #       run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - name: run tests
  #       shell: bash
  #       run: |
  #         pwd
  #         ls -al
  #         ls -l /__w/avd/
  #         # source UV3.12/bin/activate
  #         cd ansible_collections/arista/avd
  #         ansible-test units -vv

  reuse-ghcr-image:
    name: Reuse first job
    runs-on: ubuntu-latest
    needs: [ container-job ]
    steps: 
      - name: Convert GitHub username to lowercase
        id: lowercase
        run: |
          echo "::set-output name=lowercase::$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ steps.lowercase.outputs.lowercase }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Pull docker image from ghcr
      #   run: |
      #     docker pull ghcr.io/${{ steps.lowercase.outputs.lowercase }}/avd/python:3.12

      - name: Run Docker Container
        run: |
          docker run -dit --name avd-python-container ghcr.io/${{ steps.lowercase.outputs.lowercase }}/avd/python_avd:0.0.1 bash
        
      - name: Execute Ansible unit tests 3.12
        run: |
          docker exec avd-python-container bash -c "source UV3.12/bin/activate && cd avd/ansible_collections/arista/avd && ansible-test units -vv"
      
      - name: Execute Ansible integration tests 3.12
        run: |
          docker exec avd-python-container bash -c "source UV3.12/bin/activate && cd avd/ansible_collections/arista/avd && ansible-test integration -vv"

      - name: Execute Ansible integration tests 3.13
        run: |
          docker exec avd-python-container bash -c "source UV3.13/bin/activate && cd avd/ansible_collections/arista/avd && ansible-test integration -vv"
      
      - name: Execute Ansible sanity tests 3.12
        run: |
          docker exec avd-python-container bash -c "source UV3.12/bin/activate && cd avd/ansible_collections/arista/avd && ansible-test sanity --color yes -v"
      
      - name: Execute Ansible sanity tests 3.13
        run: |
          docker exec avd-python-container bash -c "source UV3.13/bin/activate && cd avd/ansible_collections/arista/avd && ansible-test sanity --color yes -v"

      - name: Stop and Remove Docker Container
        run: |
          docker stop avd-python-container
          docker rm avd-python-container

